---
- name: Facts | Installation | Populate package facts
  ansible.builtin.package_facts:
    manager: auto
  no_log: true

- name: Facts | Installation | Installation info
  ansible.builtin.set_fact:
    r_kibana_info: >-
      {{ r_kibana_info | combine(
        {'installed': _r_kibana_installed, 'version': _r_kibana_version, 'to_be_upgraded': false}
      ) }}
  vars:
    _r_kibana_installed: "{{ (ansible_facts.packages.kibana | d([]) | length) > 0 }}"
    _r_kibana_version: "{{ (ansible_facts.packages.kibana | d([]) | first).version | d('') }}"

- name: Facts | Installation | Upgrade info
  ansible.builtin.set_fact:
    r_kibana_info: "{{ r_kibana_info | combine({'to_be_upgraded': _r_kibana_to_be_upgraded}) }}"
  when: r_kibana_info.installed
  vars:
    _r_kibana_to_be_upgraded: >-
      {{ r_kibana_info.version | length > 0 and
      r_kibana_version is version( r_kibana_info.version, '>')}}
