- name: Start the kibana service
  systemd:
    name: "{{ _r_kibana_systemd_name }}"
    state: started
  notify: _r_kibana_gather_health_facts

- name: Flush handlers
  meta: flush_handlers
  when: ('start' in r_kibana_actions)

- name: Assert about status<
  assert:
    that: ('error' not in _r_kibana_status_info)