- name: Stop Elasticsearch
  ansible.builtin.include_tasks: restart/stop.yml
  when: >-
    (_r_elasticsearch_triggered_restart and
    'restart_on_configuration_change' in r_elasticsearch_actions)

- name: Stop Elasticsearch
  ansible.builtin.include_tasks: restart/start.yml
  when: >-
    (_r_elasticsearch_triggered_restart and
    'restart_on_configuration_change' in r_elasticsearch_actions)
