---
# ---- run behaviour modification ----
# action allowed in r_elasticsearch_actions
# - install
# - configure
# - stop
# - upgrade
# - start
# - uninstall
# - restart_on_configuration_change
r_elasticsearch_actions: []

# more granular configuration actions
r_elasticsearch_configure_actions: []

_r_elasticsearch_triggered_restart: false

# ---- installation variables ----
r_elasticsearch_version: '8.9.2'
r_elasticsearch_rpm_name: elasticsearch
r_elasticsearch_info:
  installed: false
  version: ''
r_elasticsearch_add_repository: true

# start && stop
r_elasticsearch_systemd_enabled: true

# generic configuration
r_elasticsearch_enforce: true
__r_elasticsearch_show_nolog: false   # only for debug purpose


# static configuration
_r_elasticsearch_config_folder: /etc/elasticsearch
## password quality settings
_r_elasticsearch_password_minlength: 12
_r_elasticsearch_password_minuppercase: 3
_r_elasticsearch_password_minlowercase: 3
_r_elasticsearch_password_mindigits: 2
_r_elasticsearch_password_minspecialchars: 1
_r_elasticsearch_password_specialchars: '!._@#'


## elasticsearch.yml configurations
r_elasticsearch_node_name: ''
r_elasticsearch_node_rack: ''
r_elasticsearch_cluster_nodes:
  - host: '{{ ansible_fqdn }}'
    name: '{{ ansible_fqdn }}'
    roles:
      - master
r_elasticsearch_cluster_name: 'es_cluster'

r_elasticsearch_configuration_ssl_certificate_authorities: ''
r_elasticsearch_configuration: {}

## keystore settings
r_elasticsearch_keystore_password:
r_elasticsearch_keystore_password_file: "{{ _r_elasticsearch_config_folder }}/keystore.password"
r_elasticsearch_keystore:
_r_elasticsearch_keystore:
  "bootstrap.password": "{{ r_elasticsearch_users_initial_elastic_password }}"

## jvm setting
r_elasticsearch_jvm_initial_heap: 1g
r_elasticsearch_jvm_maximum_heap: 1g

# admin user and password
r_elasticsearch_users_initial_elastic_password: bA3nb0g.Hyw
r_elasticsearch_users_elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
r_elasticsearch_api_password:
r_elasticsearch_users: {}

_r_elasticsearch_api_user:
    username: "{{ _r_elasticsearch_api_username }}"
    password: "{{ r_elasticsearch_api_password }}"
    metadata:
      reserved_to_automation: true
    roles:
      - superuser

# component templates
r_elasticsearch_component_templates: {}
# index templates
r_elasticsearch_index_templates: {}
# ilm policies
r_elasticsearch_ilm_policies: {}
# pipelines
r_elasticsearch_ingest_pipelines: {}
# logstash
r_elasticsearch_logstash_pipelines: {}
# roles
r_elasticsearch_roles: {}
r_elasticsearch_role_mappings: {}
