---
# ---- run behaviour modification ----
# action allowed in r_elasticsearch_actions
# - install
# - configure
# - stop
# - upgrade
# - start
# - uninstall
# - restart_on_configuration_change
r_elasticsearch_actions: []
_r_elasticsearch_actions_allowed:
 - install
 - configure
 - stop
 - upgrade
 - start
 - uninstall
 - restart_on_configuration_change

# more granular configuration actions
r_elasticsearch_configure_actions: []
_r_elasticsearch_configure_actions_allowed:
  - sysctl
  - folders
  - main_files
  - keystore
  - enforce_keystore
  - ssl
  - component_template
  - index_template
  - ilm_policies
  - users
  - roles
  - role_mappings
  - initial
  - enforce_user_password
_r_elasticsearch_triggered_restart: false

# ---- installation variables ----
r_elasticsearch_version: '8.9.2'
r_elasticsearch_rpm_name: elasticsearch
r_elasticsearch_info:
  installed: false
  version: ''
r_elasticsearch_add_repository: true

# start && stop
_r_elasticsearch_systemd_name: elasticsearch.service
r_elasticsearch_systemd_enabled: true

# generic configuration
__r_elasticsearch_show_nolog: false   # only for debug purpose


# static configuration
_r_elasticsearch_config_folder: /etc/elasticsearch
## password quality settings
_r_elasticsearch_password_minlength: 12
_r_elasticsearch_password_minuppercase: 3
_r_elasticsearch_password_minlowercase: 3
_r_elasticsearch_password_mindigits: 2
_r_elasticsearch_password_minspecialchars: 1
_r_elasticsearch_password_specialchars: '!._@#'

## linux username and password
_r_elasticsearch_username: elasticsearch
_r_elasticsearch_group: elasticsearch



## elasticsearch.yml configurations
r_elasticsearch_node_name: ''
r_elasticsearch_node_rack: ''
r_elasticsearch_cluster_nodes:
  - host: '{{ ansible_fqdn }}'
    name: '{{ ansible_fqdn }}'
    roles:
      - master
r_elasticsearch_cluster_name: 'es_cluster'

_r_elasticsearch_configuration:
  network:
    host: "0.0.0.0"
  http:
    host: "0.0.0.0"
    port: 9200
  cluster:
    name: '{{ r_elasticsearch_cluster_name }}'
    initial_master_nodes: "{{ r_elasticsearch_cluster_nodes | selectattr('roles','bartokit.elastic.contains', 'master') | map(attribute='name') | list }}"
    routing:
      allocation:
        awareness:
          attributes: site_id
  node:
    name: '{{ r_elasticsearch_node_name }}'
    roles: >-
      {{ (r_elasticsearch_cluster_nodes |
      selectattr('host', 'equalto', ansible_fqdn) | first).roles | list }}
  path:
    logs: /var/log/elasticsearch
    data: /var/lib/elasticsearch
  discovery:
    seed_hosts: "{{ r_elasticsearch_cluster_nodes | selectattr('roles','bartokit.elastic.contains', 'master') | map(attribute='host') | list }}"
  xpack:
    security:
      enabled: true
      enrollment:
        enabled: true
      http:
        ssl:
          enabled: true
          verification_mode: certificate
          keystore:
            path: certs/elastic.p12
          certificate_authorities: certs/ca.crt
      transport:
        ssl:
          enabled: true
          verification_mode: certificate
          keystore:
            path: certs/elastic.p12
          certificate_authorities: certs/ca.crt

r_elasticsearch_configuration_ssl_certificate_authorities: ''
r_elasticsearch_configuration: {}

## keystore settings
r_elasticsearch_keystore_password:
r_elasticsearch_keystore_password_file: "{{ _r_elasticsearch_config_folder }}/keystore.password"
r_elasticsearch_keystore:
_r_elasticsearch_keystore:
  "bootstrap.password": "{{ r_elasticsearch_users_initial_elastic_password }}"

## jvm setting
r_elasticsearch_jvm_initial_heap: 1g
r_elasticsearch_jvm_maximum_heap: 1g

# admin user and password
r_elasticsearch_users_initial_elastic_password: bA3nb0g.Hyw
r_elasticsearch_users_elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
r_elasticsearch_api_password:
r_elasticsearch_users: {}
_r_elasticsearch_api_user:
  ansible:
    password: "{{ r_elasticsearch_api_password }}"
    metadata:
      reserved_to_automation: true
    roles:
      - superuser

# component templates
r_elasticsearch_component_templates: {}
# index templates
r_elasticsearch_index_templates: {}
# ilm policies
r_elasticsearch_ilm_policies: {}
# roles
r_elasticsearch_roles: {}
r_elasticsearch_role_mappings: {}
