---
- name: Standalone | Converge | Beats
  hosts: beats
  tags:
    - beats
  gather_facts: false
  tasks:
    - name: Read configurations
      ansible.builtin.include_tasks: ../elasticsearch_configuration.yml

    - name: Read configurations
      ansible.builtin.include_tasks: ../beats_configuration.yml


    - name: Test the installation, configuration and product start
      ansible.builtin.set_fact:
        r_beat_actions:
          - install
          - configure
          - start
        r_beat_configure_actions:
          - main_files
          - keystore
          - modules
          - inputs
          - monitors

    - name: Test file beat
      ansible.builtin.include_role:
        name: bartokit.elastic.beat
      vars:
        r_beat_type: file
        __r_beat_show_nolog: true
        r_beat_configuration: "{{ filebeat.configuration }}"
        r_beat_keystore:
          elastic_user: elastic
          elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
        r_beat_modules: "{{ filebeat.r_beat_modules }}"
        r_beat_inputs: "{{ filebeat.r_beat_inputs }}"

    - name: Test audit beat
      ansible.builtin.include_role:
        name: bartokit.elastic.beat
      vars:
        r_beat_type: audit
        __r_beat_show_nolog: true
        r_beat_configuration: "{{ auditbeat.configuration }}"
        r_beat_keystore:
          elastic_user: elastic
          elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
        r_beat_configure_actions:
          - main_files
          - keystore
          - modules

    - name: Test metric beat
      ansible.builtin.include_role:
        name: bartokit.elastic.beat
      vars:
        r_beat_type: metric
        __r_beat_show_nolog: true
        r_beat_configuration: "{{ metricbeat.configuration }}"
        r_beat_keystore:
          elastic_user: elastic
          elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
        r_beat_modules: "{{ metricbeat.r_beat_modules }}"

    - name: Test heart beat
      ansible.builtin.include_role:
        name: bartokit.elastic.beat
      vars:
        r_beat_type: heart
        __r_beat_show_nolog: true
        r_beat_configuration: "{{ metricbeat.configuration }}"
        r_beat_keystore:
          elastic_user: elastic
          elastic_password: "{{ r_elasticsearch_users_initial_elastic_password }}"
        r_beat_monitors: "{{ heartbeat.r_beat_monitors }}"

- name: Standalone | Converge | Elasticsearch
  hosts: cluster
  tags:
    - elastic
  gather_facts: false
  tasks:

    - name: Read configurations
      ansible.builtin.include_tasks: ../elasticsearch_configuration.yml

    - name: Test the installation, configuration and product start
      ansible.builtin.set_fact:
        r_elasticsearch_actions:
          - install
          - configure
          - start
          - restart_on_configuration_change
        r_elasticsearch_configure_actions:
          - folders
          - main_files
          - keystore
          - ssl
          - enforce_keystore
          - enforce_user_password
          - component_template
          - index_template
          - ilm_policies
          - users
          - initial
          - beats_index_management
          - ingest_pipelines
          - logstash_pipelines
          - roles
          - role_mappings

    - name: Replace this task with one that validates your content
      ansible.builtin.include_role:
        name: bartokit.elastic.elasticsearch

- name: Standalone | Converge | Kibana
  hosts: kibanas
  tags:
    - kibana
  gather_facts: false
  tasks:
    - name: Read configurations
      ansible.builtin.include_tasks: ../kibana_configuration.yml

    - name: Test the installation, configuration and product start
      ansible.builtin.set_fact:
        r_kibana_actions:
          - install
          - configure
          - start
          # - restart_on_configuration_change
        r_kibana_configure_actions:
          - folders
          - main_files
          - ssl
          - spaces
          - data_views
          - beat_dashboards

    - name: Replace this task with one that validates your content
      ansible.builtin.include_role:
        name: bartokit.elastic.kibana


- name: Standalone | Converge | Kibana
  hosts: logstash
  tags:
    - logstash
  gather_facts: false
  tasks:
    - name: Read configurations
      ansible.builtin.include_tasks: ../logstash_configuration.yml

    - name: Test the installation, configuration and product start
      ansible.builtin.set_fact:
        r_logstash_actions:
          - install
          - configure
          # - start
          # - restart_on_configuration_change
        r_logstash_configure_actions:
          - folders
          - main_files
          - ssl
        #   - enforce_keystore
        #   - component_template
        #   - index_template
        #   - ilm_policies
        #   - users

    - name: Replace this task with one that validates your content
      ansible.builtin.include_role:
        name: bartokit.elastic.logstash
