---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: standalone
    image: registry.access.redhat.com/ubi8/ubi-init
    groups:
      - cluster
    network: molecule-elastic-search-test
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    tmpfs:
      - /run
    pre_build_image: true

provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    host_vars:
      standalone:
        ansible_host: standalone
        node: standalone
        roles:
          - master
          - data
