---
- name: Beat configuration
  ansible.builtin.set_fact:
    filebeat_configuration:
      filebeat.inputs:
        - type: filestream
          id: dnf
          paths:
            - "/var/log/dnf.log"
      output.elasticsearch:
        hosts:
          - "https://elastic:9200"
        username: "${elastic_user}"
        password: "${elastic_password}"
