---
- name: Beat configuration
  ansible.builtin.set_fact:
    r_beat_modules:
      auditd:
      zookeeper:
    r_beat_inputs:
      - type: filestream
        id: dnf
        paths:
          - "/var/log/dnf.log"
        index: beattest
    filebeat_configuration:
      output.elasticsearch:
        hosts:
          - "https://elastic:9200"
        username: "${elastic_user}"
        password: "${elastic_password}"
