---
- name: Beat configuration
  ansible.builtin.set_fact:
    r_beat_version: 8.16.1-1
    filebeat:
      r_beat_modules:
        auditd:
          - module: auditd
            log:
              enabled: false
        zookeeper:
      r_beat_inputs:
        dnf:
          - type: filestream
            id: dnf
            paths:
              - "/var/log/dnf.log"
            index: beattest
      configuration:
        output.elasticsearch:
          hosts:
            - "https://elastic:9200"
          username: "${elastic_user}"
          password: "${elastic_password}"
    auditbeat:
      configuration:
        output.elasticsearch:
          hosts:
            - "https://elastic:9200"
          username: "${elastic_user}"
          password: "${elastic_password}"
    metricbeat:
      r_beat_modules:
        system:
          - module: system
            metricsets:
              - cpu
              - load
              - memory
              - network
              - process
              - process_summary
              - uptime
              - socket_summary
            enable: true
      configuration:
        output.elasticsearch:
          hosts:
            - "https://elastic:9200"
          username: "${elastic_user}"
          password: "${elastic_password}"
    heartbeat:
      r_beat_monitors:
        localhost:
          - type: icmp # monitor type `icmp` (requires root) uses ICMP Echo Request to ping
            id: my-monitor
            name: my-icmp-monitor
            schedule: '*/5 * * * * * *' # exactly every 5 seconds like 10:00:00, 10:00:05, ...
            hosts: ["localhost"]
            ipv4: true
            ipv6: true
            mode: any
            timeout: 16s
            wait: 1s
      configuration:
        output.elasticsearch:
          hosts:
            - "https://elastic:9200"
          username: "${elastic_user}"
          password: "${elastic_password}"
