---
- name: Get certificate
  ansible.builtin.slurp:
    path: /etc/pki/tls/certs/ca-certificate.pem
  register: _converge_ca_certificate

- name: Cluster configuration
  ansible.builtin.set_fact:
    r_elasticsearch_cluster_name: molecule_cluster
    r_elasticsearch_node_rack: rotating
    r_elasticsearch_cluster_nodes: >-
      {%- filter list -%}
        [{%- for node in groups.cluster -%}
            { 'host': '{{ node }}', 'name': '{{ node }}', 'roles': {{ hostvars[node].roles }} },
      {%- endfor -%}]{%- endfilter -%}
    r_elasticsearch_users_initial_elastic_password: bA3nb0g.Hyw
    r_elasticsearch_keystore_password: 'adfs8NSM2nc.ug'
    r_elasticsearch_keystore:
      keystore.seed: 'J=Z4Y50EUvoAUS?^rQ_@'
      xpack.security.http.ssl.keystore.secure_password: 'XC9sxbnkTzCP9aTEc74LfQ'
      xpack.security.transport.ssl.keystore.secure_password: XC9sxbnkTzCP9aTEc74LfQ
      xpack.security.transport.ssl.truststore.secure_password: XC9sxbnkTzCP9aTEc74LfQ
      # test.secure.key: passwd1
    r_elasticsearch_configuration_ssl_certificate_authorities: "{{ _converge_ca_certificate.content | b64decode }}"
    r_elasticsearch_api_password: 'ansiblepassword'
    r_elasticsearch_configuration:
      xpack:
        security:
          audit:
            enabled: false
    r_elasticsearch_component_templates:
      template1:
        _meta:
          author: 'BartokIT'
        template:
          mappings:
            properties:
              order_date:
                type: 'date'
                format: 'dd-MM-yyyy'
          settings:
            number_of_shards: 1
      beattest-ct:
        _meta:
          author: 'BartokIT'
        template:
          settings:
            index.lifecycle.name: beattest-ilm
    r_elasticsearch_index_templates:
      template1:
        index_patterns:
          - custom*
        template:
          settings:
            number_of_shards: 3
        _meta:
          author: 'BartokIT'
      beattest:
        index_patterns:
          - beattest*
        composed_of:
          - beattest-ct
    r_elasticsearch_ilm_policies:
      beattest-ilm:
        phases:
          hot:
            min_age: "0ms"
            actions:
              rollover:
                max_age: "30d"
                max_primary_shard_size: "50gb"
      policy1:
        _meta:
          author: 'BartokIT'
        phases:
          hot:
            actions:
              rollover:
                max_primary_shard_size: "50gb"
          warm:
            min_age: "30d"
            actions:
              shrink:
                number_of_shards: 1
              forcemerge:
                max_num_segments: 1
          delete:
            min_age: "735d"
            actions:
              delete: {}
      filebeat:
        phases:
          hot:
            min_age: "0ms"
            actions:
              rollover:
                max_age: "30d"
                max_primary_shard_size: "50gb"
    r_elasticsearch_users:
      mytestuser:
        password: unknown.1234
        roles:
        full_name: test user
