---
- name: Get certificate
  ansible.builtin.slurp:
    path: /etc/pki/tls/certs/ca-certificate.pem
  register: _converge_ca_certificate

- name: Cluster configuration
  ansible.builtin.set_fact:
    r_elasticsearch_cluster_nodes: >-
      {%- filter list -%}
        [{%- for node in groups.cluster -%}
            { 'host': '{{ node }}', 'name': '{{ node }}', 'roles': {{ hostvars[node].roles }} },
      {%- endfor -%}]{%- endfilter -%}
    r_elasticsearch_keystore_password: 'adfs8NSM2nc.ug'
    r_elasticsearch_keystore:
      keystore.seed: 'J=Z4Y50EUvoAUS?^rQ_@'
      xpack.security.http.ssl.keystore.secure_password: 'uesl3NAZSCKEZ_Hzfr7CPg'
      xpack.security.transport.ssl.keystore.secure_password: XC9sxbnkTzCP9aTEc74LfQ
      xpack.security.transport.ssl.truststore.secure_password: XC9sxbnkTzCP9aTEc74LfQ
    r_elasticsearch_configuration_ssl_certificate_authorities: "{{ _converge_ca_certificate.content | b64decode }}"
