---
- name: Get ca certificate
  ansible.builtin.slurp:
    path: /etc/pki/tls/certs/ca-certificate.pem
  register: _converge_ssl_ca_certificate

- name: Get key
  ansible.builtin.slurp:
    path: /etc/pki/tls/private/logstash.key
  register: _converge_ssl_key

- name: Get certificate
  ansible.builtin.slurp:
    path: /etc/pki/tls/certs/logstash.pem
  register: _converge_ca_certificate

- name: Cluster configuration
  ansible.builtin.set_fact:
    r_logstash_version: '8.17.0-1'
    r_logstash_enforce: true
    r_logstash_cluster_name: molecule_cluster
    r_logstash_node_rack: rotating
    r_logstash_keystore_password: 'adfs8NSM2nc.ug'
    r_logstash_keystore: {}
      # test.secure.key: passwd1
    r_logstash_configuration_ssl_certificate_authorities: "{{ _converge_ssl_ca_certificate.content | b64decode }}"
    r_logstash_configuration_ssl_key: "{{ _converge_ssl_key.content | b64decode }}"
    r_logstash_configuration_ssl_certificate: "{{ _converge_ca_certificate.content | b64decode }}"
    r_logstash_api_password: 'ansiblepassword'
    r_logstash_pipelines_confd:
      testpipeline: |
        input { stdin { } }
        output {
          stdout { codec => rubydebug }
        }
    r_logstash_configuration: {}
