---
# tasks file for elasticsearch
- name: Gather fact and sanity checks
  ansible.builtin.include_tasks: facts/main.yml

- name: Install Kibana
  ansible.builtin.include_tasks: install/main.yml
  when: ('install' in r_kibana_actions | list )

- name: Configure static files
  ansible.builtin.include_tasks: configure/static.yml
  when: ('configure' in r_kibana_actions)

- name: Restart Kibana (for reconfiguration)
  ansible.builtin.include_tasks: restart/restart.yml
  when: >-
    (_r_kibana_triggered_restart and
    'restart_on_configuration_change' in r_kibana_actions)

- name: Stop Kibana
  ansible.builtin.include_tasks: restart/stop.yml
  when: ('stop' in r_kibana_actions)

- name: Start Kibana
  ansible.builtin.include_tasks: restart/start.yml
  when: ('start' in r_kibana_actions)

- name: Configure static files
  ansible.builtin.include_tasks: configure/dynamic.yml
  when: ('configure' in r_kibana_actions)