---
- name: Facts | Health | Populate service facts
  ansible.builtin.service_facts:

- name: Facts | Health | Startup info
  ansible.builtin.set_fact:
    r_elasticsearch_info: "{{ r_elasticsearch_info | combine({'started': _r_elasticsearch_started}) }}"
  vars:
    _r_elasticsearch_started: "{{ (ansible_facts.services['elasticsearch.service'] | d({'state': ''})).state == 'running' }}"

- name: Facts | Health | Gather information
  bartokit.elastic.elasticsearch_info:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    gather_subset:
      - health
      - license
      - cluster_health
    ssl_verify: false
  register: _r_elasticsearch_status_info
  when: r_elasticsearch_info.started
