---
- name: Gather information
  bartokit.elastic.elasticsearch_info:
    user: 'elastic'
    password: "{{ r_elasticsearch_users_initial_elastic_password | d(omit) }}"
    gather_subset:
      - health
      - license
      - cluster_health
    ssl_verify: false
  register: _r_elasticsearch_status_info
- fail: