---
- name: Facts | Installation | Populate package facts
  ansible.builtin.package_facts:
    manager: auto
  no_log: true

- name: Facts | Installation | Installation info
  ansible.builtin.set_fact:
    r_elasticsearch_info: "{{ r_elasticsearch_info | combine({'installed': _r_elasticsearch_installed, 'version': _r_elasticsearch_version}) }}"
  vars:
    _r_elasticsearch_installed: "{{ (ansible_facts.packages.elasticsearch | d([]) | length) > 0 }}"
    _r_elasticsearch_version: "{{ (ansible_facts.packages.elasticsearch | d([]) | first).version | d('') }}"


