---
- name: Facts | Perform basic setup
  ansible.builtin.setup:
    gather_subset:
      - min
  when: ansible_fqdn is not defined

- name: Facts | Actions that will be performed
  ansible.builtin.debug:
    msg: "{{ r_elasticsearch_actions }}"

- name: Facts | Include installation facts gather
  ansible.builtin.include_tasks: facts/installation.yml

- name: Facts | Include variable sanity checks
  ansible.builtin.include_tasks: facts/sanity.yml

- name: Facts | Include installation facts gather
  ansible.builtin.include_tasks: facts/installation.yml

- name: Facts | Include healt facts gather
  ansible.builtin.include_tasks: facts/health.yml
  when: r_elasticsearch_info.started