---
- name: Facts | Perform basic setup
  ansible.builtin.setup:
    gather_subset:
      - min
  when: ansible_fqdn is not defined

- name: Facts | Installation | Installation info
  ansible.builtin.set_fact:
    r_elasticsearch_info:
      installed: false
      version: ''
      started: false

- name: Facts | Actions that will be performed
  ansible.builtin.debug:
    msg: "{{ r_elasticsearch_actions }}"

- name: Facts | Include installation facts gather
  ansible.builtin.include_tasks: facts/installation.yml

- name: Facts | Include variable sanity checks
  ansible.builtin.include_tasks: facts/sanity.yml

- name: Facts | Include installation facts gather
  ansible.builtin.include_tasks: facts/installation.yml

- name: Facts | Include health facts gather
  ansible.builtin.include_tasks: facts/health.yml
  when: r_elasticsearch_info.installed

- name: Facts | Installation | Print information   # noqa jinja[spacing]
  ansible.builtin.debug:
    msg: "{{ _r_elasicsearch_info.split('|') }}"
  vars:
    _r_elasicsearch_info: >-
        Installed: {{ r_elasticsearch_info.installed }}
        |Requested version:   {{ r_elasticsearch_version }}
        {%- if r_elasticsearch_info.installed -%}
        |Version:   {{ r_elasticsearch_info.version }}
        |Started:   {{ r_elasticsearch_info.started }}
        |To be upgraded:   {{ r_elasticsearch_info.to_be_upgraded }}
        {%- endif -%}