---
# configuration assert
- name: Sanity check configuration variables
  when: ('configure' in r_elasticsearch_actions)
  block:
    - name: Facts | Sanity | Assertion about node name
      ansible.builtin.assert:
        that:
          - "{{ ansible_fqdn in (r_elasticsearch_cluster_nodes | map(attribute='host') | list) }}"
          - (r_elasticsearch_cluster_nodes | selectattr('host', '==', ansible_fqdn) | first).name | d(false, true)
        msg: Current host ({{ ansible_fqdn }}) is not present inside the cluster nodes list

    - name: Facts | Sanity | Assertion about keystore password quality
      ansible.builtin.assert:
        that:
          - >-
            r_elasticsearch_keystore_password | length >=
            _r_elasticsearch_password_minlength
          - >-
            r_elasticsearch_keystore_password is
            regex("([a-z].*){" ~ _r_elasticsearch_password_minlowercase ~ "}")
          - >-
            r_elasticsearch_keystore_password is
            regex("([A-Z].*){" ~ _r_elasticsearch_password_minuppercase ~ "}")
          - >-
            r_elasticsearch_keystore_password is
            regex("([0-9].*){" ~ _r_elasticsearch_password_mindigits ~ "}")
          - >-
            r_elasticsearch_keystore_password is
            regex("([" ~ _r_elasticsearch_password_specialchars ~ ".*]){" ~ _r_elasticsearch_password_minspecialchars ~ "}")
        msg:
          - "Please set the keystore password and ensure correct strength"
          - "Password must have minimum length of {{ _r_elasticsearch_password_minlength }}"
          - "Password must at least of {{ _r_elasticsearch_password_minlowercase }} lower case chars"
          - "Password must at least of {{ _r_elasticsearch_password_minuppercase }} upper case chars"
          - "Password must at least of {{ _r_elasticsearch_password_mindigits }} digits"
          - "Password must at least of {{ _r_elasticsearch_password_minspecialchars }} special chars choosed from {{ _r_elasticsearch_password_specialchars }}"
      when: r_elasticsearch_keystore_password | d(false, true)

    - name: Facts | Sanity | Set elatic node
      ansible.builtin.set_fact:
        r_elasticsearch_node_name: "{{ (r_elasticsearch_cluster_nodes | selectattr('host', '==', ansible_fqdn) | first).name }}"
        r_elasticsearch_node_rack: "{{ (r_elasticsearch_cluster_nodes | selectattr('host', '==', ansible_fqdn) | first).rack | d(omit) }}"
      no_log: "{{ not (__r_elasticsearch_show_nolog | bool) }}"

    - name: Facts | Sanity | Combine elasticsearch configurations with defaults
      ansible.builtin.set_fact:
        r_elasticsearch_keystore: "{{ r_elasticsearch_keystore | combine(_r_elasticsearch_keystore) }}"
        r_elasticsearch_configuration: "{{ _r_elasticsearch_configuration | combine(r_elasticsearch_configuration, recursive=True) }}"

    - name: Facts | Sanity | Combine rack awareness variable
      ansible.builtin.set_fact:
        r_elasticsearch_configuration: "{{ r_elasticsearch_configuration | combine({ 'node': { 'attr': { r_elasticsearch_configuration.cluster.routing.allocation.awareness.attributes: r_elasticsearch_node_rack }}}, recursive=True) }}"
      when: r_elasticsearch_node_rack

    - name: Facts | Sanity | Ensure SSL configuration correctness
      ansible.builtin.assert:
        that:
          - >-
            r_elasticsearch_configuration.xpack.security.http.ssl.keystore.path ==
            r_elasticsearch_configuration.xpack.security.transport.ssl.keystore.path
          - >-

      when:
        - r_elasticsearch_configuration.xpack.security.enabled | bool
        - r_elasticsearch_configuration.xpack.security.http.ssl.enabled | bool or
          r_elasticsearch_configuration.xpack.security.transport.ssl.enabled | bool

# validation of the configuration
- name: Include variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ r_elasticsearch_version | regex_replace('^([0-9])\\.([0-9]*).*', '\\1.\\2') }}.yml"
        - main.yml
      paths:
        - "vars"

- name: Check the validity of the configuration
  assert:
    that: "{{ r_elasticsearch_configuration is bartokit.elastic.validate_configuration(_r_elasticsearch_configuration_schema) }}"
