---
- name: Facts | Installation | Populate package facts
  ansible.builtin.package_facts:
    manager: auto
  no_log: true

- name: Facts | Installation | Installation info
  ansible.builtin.set_fact:
    r_beat_info: >-
      {{ r_beat_info | combine({
        'installed': _r_beat_info_installed,
        'version': _r_beat_info_version
      })
      }}
  vars:
    _r_beat_info_installed: "{{ ( ansible_facts.packages[r_beat_rpm_name] | d([]) | length) > 0 }}"
    _r_beat_info_version: "{{ (ansible_facts.packages[r_beat_type ~ 'beat'] | d([]) | first).version | d('') | trim }}"
