---
- name: Facts | Main | Gather facts
  ansible.builtin.setup:
    gather_subset:
      - distribution_major_version
  when: distribution_major_version is not defined

- name: Facts | Main | Initialization
  ansible.builtin.set_fact:
    r_beat_info:
      installed: false
      version: ''
      started: false

- name: Facts | Include variable sanity checks
  ansible.builtin.include_tasks: facts/sanity.yml

- name: Facts | Include installation facts gather
  ansible.builtin.include_tasks: facts/installation.yml

- name: Facts | Include health facts gather
  ansible.builtin.include_tasks: facts/health.yml
  when: r_beat_info.installed

- name: Facts | Installation | Print information   # noqa jinja[spacing]
  ansible.builtin.debug:
    msg: "{{ _r_elasicsearch_info.split('|') }}"
  vars:
    _r_elasicsearch_info: >-
        Beat: {{ r_beat_type }}beat
        |Installed: {{ r_beat_info.installed }}
        {%- if r_beat_info.installed -%}
        |Version:   {{ r_beat_info.version }}
        |Started:   {{ r_beat_info.started }}
        {%- endif -%}
