---
# ---- run behaviour modification ----
# action allowed in r_kibana_actions
# - install
# - configure
# - stop
# - upgrade
# - start
# - uninstall
# - restart_on_configuration_change
r_kibana_actions: []
_r_kibana_actions_allowed:
  - install
  - configure
  - stop
  - upgrade
  - start
  - uninstall
  - restart_on_configuration_change

# more granular configuration actions
r_kibana_configure_actions: []
_r_kibana_configure_actions_allowed:
  - folders
  - sysctl
  - main_files
  - keystore
  - ssl
  - spaces
  - data_views
  - beat_dashboards
_r_kibana_triggered_restart: false

# ---- installation variables ----
r_kibana_version: '8.11.2'
r_kibana_rpm_name: kibana
r_kibana_info:
  installed: false
  version: ''
r_kibana_add_repository: true

# start && stop
_r_kibana_systemd_name: kibana.service

# generic configuration
__r_kibana_show_nolog: false   # only for debug purpose


# static configuration
_r_kibana_config_folder: /etc/kibana

## linux username and password
_r_kibana_username: kibana
_r_kibana_group: kibana



## elasticsearch.yml configurations
r_kibana_node_name: ''
r_kibana_node_rack: ''
r_kibana_cluster_nodes:
  - host: '{{ ansible_fqdn }}'
    name: '{{ ansible_fqdn }}'
    roles:
      - master
r_kibana_cluster_name: 'es_cluster'

_r_kibana_configuration:
  elasticsearch:
    hosts: "{{ r_kibana_elasticsearch_nodes }}"
  server:
    name: '{{ r_kibana_node_name }}'
    host: '{{ r_kibana_node_name }}'
  path:
    data: /var/lib/kibana
  logging:
    root:
      appenders:
        - kibana
    appenders:
      kibana:
        type: file
        fileName: /var/log/kibana/kibana.log
        layout:
          type: pattern

r_kibana_configuration_ssl_certificate_authorities: ''
r_kibana_configuration_ssl_key: ''
r_kibana_configuration_ssl_certificate: ''
r_kibana_configuration: {}

## keystore settings
r_kibana_keystore_password:
r_kibana_keystore_password_file: "{{ _r_kibana_config_folder }}/keystore.password"
r_kibana_keystore:
_r_kibana_keystore: []
## password quality settings
_r_kibana_password_minlength: 12
_r_kibana_password_minuppercase: 3
_r_kibana_password_minlowercase: 3
_r_kibana_password_mindigits: 2
_r_kibana_password_minspecialchars: 1
_r_kibana_password_specialchars: '!._@#'

## jvm setting
r_kibana_jvm_initial_heap: 1g
r_kibana_jvm_maximum_heap: 1g

# admin user and password
_r_kibana_api_username: ansible
r_kibana_api_password: ansible
_r_kibana_api_user:
    username: "{{ _r_kibana_api_username }}"
    password: "{{ r_kibana_api_password }}"

# configuration
r_kibana_enforce: false
r_kibana_spaces: {}
r_kibana_dataviews: {}