---
- name: Check that Beat is installed
  ansible.builtin.assert:
    that:
      - r_beat_info.installed
    msg: "Please install first the product"

- name: Folder management
  when: ('folders' in r_beat_configure_actions)
  block:
    - name: Create needed folders
      ansible.builtin.file:
        state: directory
        path: "{{ _r_beat_loop_folders.path }}"
        owner: "root"
        group: "root"
        mode: "{{ _r_beat_loop_folders.mode }}"
      loop:
        - path: "{{ r_beat_input_path }}"
          mode: '755'
        - path: "{{ r_beat_modules_path }}"
          mode: '755'
      loop_control:
        loop_var: _r_beat_loop_folders

- name: Main configuration files
  when: ('main_files' in r_beat_configure_actions )
  block:
    - name: Write configuration file
      ansible.builtin.template:
        src: beat.yml.j2
        dest: "{{ _r_beat_config_folder }}/{{ r_beat_type }}beat.yml"
        mode: 0600
        owner: root
        group: root
      notify:
        _r_beat_configuration_changed

- name: Manage keystore
  bartokit.elastic.beat_keystore:
    force: "{{  'enforce_keystore' in r_beat_configure_actions }}"
    credentials: "{{ r_beat_keystore }}"
    type: "{{ r_beat_type }}"
  when:
    - ('keystore' in r_beat_configure_actions)


- name: Flush handlers
  meta: flush_handlers