---
# vars file for elasticsearch
_r_elasticsearch_systemd_name: elasticsearch.service

_r_elasticsearch_actions_allowed:
 - install
 - configure
 - stop
 - upgrade
 - start
 - uninstall
 - restart_on_configuration_change

_r_elasticsearch_configure_actions_allowed:
  - sysctl
  - folders
  - main_files
  - keystore
  - enforce_keystore
  - ssl
  - component_template
  - index_template
  - ilm_policies
  - users
  - roles
  - role_mappings
  - initial
  - enforce_user_password
  - ingest_pipelines
  - logstash_pipelines
