---

- name: Install the product
  when: >-
    not r_elasticsearch_info.installed or
    r_elasticsearch_info.to_be_upgraded
  block:
    - name: Add the public repository
      when: r_elasticsearch_add_repository | bool
      block:
        - name: Import the repository key
          ansible.builtin.rpm_key:
            state: present
            key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

        - name: Add the repository
          ansible.builtin.yum_repository:
            name: elastic8
            description: Elasticsearch repository for 8.x packages
            file: elasticsearch
            baseurl: https://artifacts.elastic.co/packages/8.x/yum
            enabled: true
            gpgcheck: false

    - name: Install | Install expect and python modules
      ansible.builtin.dnf:
        name:
          - python3-cryptography
          - expect
        state: present

    - name: Install | Install Elasticsearch
      ansible.builtin.dnf:
        name: '{{ r_elasticsearch_rpm_name }}-{{ r_elasticsearch_version }}'
        state: present
      notify:
        - _r_elasticsearch_gather_installation_facts

- name: Install | Install Beats
  ansible.builtin.dnf:
    name: >-
      {{ _r_elasticsearch_loop_beat.name }}
      {%- if _r_elasticsearch_loop_beat.version is defined -%}-{{ _r_elasticsearch_loop_beat.version }}{%- endif -%}
    state: present
  loop: '{{ r_elasticsearch_beat_index_management_setup }}'
  loop_control:
    loop_var: _r_elasticsearch_loop_beat


- name: Flush handlers
  ansible.builtin.meta: flush_handlers
