---
# tasks file for elasticsearch
- name: Gather fact and sanity checks
  ansible.builtin.include_tasks: facts/main.yml

- name: Manage ILM polices
  bartokit.elastic.elasticsearch_index_lifecycle_policy:
    user: 'elastic'
    password: "{{ r_elasticsearch_users_initial_elastic_password | d(omit) }}"
    ssl_verify: false
    policies: "{{ r_elasticsearch_ilm_policies }}"
  run_once: true
  when: ('ilm_policies' in r_elasticsearch_configure_actions)
- fail:

- name: Install Elasticsearch
  ansible.builtin.include_tasks: install/main.yml
  when: ('install' in r_elasticsearch_actions | list )

- name: Configure static files
  ansible.builtin.include_tasks: configure/static.yml
  when: ('configure' in r_elasticsearch_actions)

- name: Restart Elasticsearch (for reconfiguration)
  ansible.builtin.include_tasks: restart/restart.yml
  when: >-
    (_r_elasticsearch_triggered_restart and
    'restart_on_configuration_change' in r_elasticsearch_actions)

- name: Stop Elasticsearch
  ansible.builtin.include_tasks: restart/stop.yml
  when: ('stop' in r_elasticsearch_actions)

- name: Start Elasticsearch
  ansible.builtin.include_tasks: restart/start.yml
  when: ('start' in r_elasticsearch_actions)

- name: Configure static files
  ansible.builtin.include_tasks: configure/dynamic.yml
  when: ('configure' in r_elasticsearch_actions)