---
# tasks file for elasticsearch
- name: Gather fact and sanity checks
  ansible.builtin.include_tasks: facts/main.yml

- name: Install Elasticsearch
  ansible.builtin.include_tasks: install/main.yml
  when: ('install' in r_elasticsearch_actions)

- name: Configure static files
  ansible.builtin.include_tasks: configure/static.yml
  when: ('configure' in r_elasticsearch_actions)

- name: Start Elasticsearch
  ansible.builtin.include_tasks: start/start.yml
  when: >-
    ('start' in r_elasticsearch_actions) or
    (_r_elasticsearch_triggered_restart and
    'restart_on_configuration_change' in r_elasticsearch_actions)

- name: Stop Elasticsearch
  ansible.builtin.include_tasks: stop/stop.yml
  when: >-
    ('stop' in r_elasticsearch_actions) or
    (_r_elasticsearch_triggered_restart and
    'restart_on_configuration_change' in r_elasticsearch_actions)
