---
- name: Check that Elasticsearch is started
  ansible.builtin.assert:
    that:
      - r_elasticsearch_info.started
    msg: "Please start first the product"

- name: Create automation user
  bartokit.elastic.elasticsearch_users:
    user: 'elastic'
    password: "xxxxxx"
    ssl_verify: false
    users: "{{ _r_elasticsearch_api_user | bartokit.elastic.dictofdict2listofdict('username') }}"
    mode: present
  run_once: true
  when: ('initial' in r_elasticsearch_configure_actions)

- name: Manage users
  bartokit.elastic.elasticsearch_users:
    user: '{{ _r_elasticsearch_api_user.keys() | first }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    users: "{{ r_elasticsearch_users | bartokit.elastic.dictofdict2listofdict('username') }}"
  run_once: true
  when: ('users' in r_elasticsearch_configure_actions)

- name: Manage ILM polices
  bartokit.elastic.elasticsearch_index_lifecycle_policies:
    user: '{{ _r_elasticsearch_api_user.keys() | first }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    policies: "{{ r_elasticsearch_ilm_policies }}"
  run_once: true
  when: ('ilm_policies' in r_elasticsearch_configure_actions)


- name: Manage component template
  bartokit.elastic.elasticsearch_component_templates:
    user: '{{ _r_elasticsearch_api_user.keys() | first }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    component_templates: "{{ r_elasticsearch_component_templates }}"
  run_once: true
  when: ('component_template' in r_elasticsearch_configure_actions)

- name: Manage index template
  bartokit.elastic.elasticsearch_index_templates:
    user: '{{ _r_elasticsearch_api_user.keys() | first }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    templates: "{{ r_elasticsearch_index_templates }}"
  run_once: true
  when: ('index_template' in r_elasticsearch_configure_actions)