---
- name: Check that Elasticsearch is started
  ansible.builtin.assert:
    that:
      - r_elasticsearch_info.started
    msg: "Please start first the product"

- name: Manage users
  bartokit.elastic.elasticsearch_users:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    users: "{{ r_elasticsearch_users | bartokit.elastic.dictofdict2listofdict('username') }}"
    enforce_password: "{{ 'enforce_user_password' in r_elasticsearch_configure_actions}}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('users' in r_elasticsearch_configure_actions)

- name: Manage ILM polices
  bartokit.elastic.elasticsearch_index_lifecycle_policies:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    policies: "{{ r_elasticsearch_ilm_policies }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('ilm_policies' in r_elasticsearch_configure_actions)

- name: Manage component template
  bartokit.elastic.elasticsearch_component_templates:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    component_templates: "{{ r_elasticsearch_component_templates }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('component_template' in r_elasticsearch_configure_actions)

- name: Manage index template
  bartokit.elastic.elasticsearch_index_templates:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    templates: "{{ r_elasticsearch_index_templates }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('index_template' in r_elasticsearch_configure_actions)

- name: Manage ingest pipelines
  bartokit.elastic.elasticsearch_ingest_pipelines:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    pipelines: "{{ r_elasticsearch_ingest_pipelines }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('ingest_pipelines' in r_elasticsearch_configure_actions)

- name: Manage logstash pipelines
  bartokit.elastic.elasticsearch_logstash_pipelines:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    pipelines: "{{ r_elasticsearch_logstash_pipelines }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('logstash_pipelines' in r_elasticsearch_configure_actions)

- name: Manage roles
  bartokit.elastic.elasticsearch_roles:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    roles: "{{ r_elasticsearch_roles }}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('roles' in r_elasticsearch_configure_actions)

- name: Manage role mappings
  bartokit.elastic.elasticsearch_role_mappings:
    user: '{{ _r_elasticsearch_api_username }}'
    password: "{{ r_elasticsearch_api_password }}"
    ssl_verify: false
    role_mappings: "{{ r_elasticsearch_role_mappings}}"
    mode: "{{ (r_elasticsearch_enforce | bool) | ternary('multiple','present') }}"
  run_once: true
  when: ('role_mappings' in r_elasticsearch_configure_actions)
