---
- name: Check that Elasticsearch is started
  ansible.builtin.assert:
    that:
      - r_elasticsearch_info.started
    msg: "Please start first the product"

- name: Manage component template
  bartokit.elastic.elasticsearch_component_template:
    user: 'elastic'
    password: "{{ r_elasticsearch_users_initial_elastic_password | d(omit) }}"
    ssl_verify: false
    component_templates: "{{ r_elasticsearch_component_templates }}"
  run_once: true
  when: ('component_template' in r_elasticsearch_configure_actions)

- name: Manage index template
  bartokit.elastic.elasticsearch_index_template:
    user: 'elastic'
    password: "{{ r_elasticsearch_users_initial_elastic_password | d(omit) }}"
    ssl_verify: false
    templates: "{{ r_elasticsearch_index_templates }}"
  run_once: true
  when: ('index_template' in r_elasticsearch_configure_actions)