---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/requirements.yml
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: master1
    image: registry.access.redhat.com/ubi8/ubi-init
    groups:
      - cluster
    network: molecule-elastic-search-test
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    tmpfs:
      - /run
    pre_build_image: true
  - name: master2
    image: registry.access.redhat.com/ubi8/ubi-init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    groups:
      - cluster
    network: molecule-elastic-search-test
    tmpfs:
      - /run
    pre_build_image: true
  - name: master3
    image: registry.access.redhat.com/ubi8/ubi-init
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
    command: "/usr/sbin/init"
    groups:
      - cluster
    network: molecule-elastic-search-test
    tmpfs:
      - /run
    pre_build_image: true
provisioner:
  name: ansible
  options:
    diff: true
  inventory:
    host_vars:
      master1:
        ansible_host: master1
        node: master1
        roles:
          - master
      master2:
        ansible_host: master2
        node: master2
        roles:
          - master
      master3:
        ansible_host: master3
        node: master3
        roles:
          - master
