---
- name: Configure | Static | Check that Elasticsearch is installed
  ansible.builtin.assert:
    that:
      - r_kibana_info.installed
    msg: "Please install first the product"

- name: Configure | Static | Kernel parameters
  when: ('sysctl' in r_kibana_configure_actions)
  block:
    - ansible.posix.sysctl:
        name: vm.max_map_count
        value: '262144'
        sysctl_set: true
        state: present
        reload: true

- name: Configure | Static | Folder management
  when: ('folders' in r_kibana_configure_actions)
  block:
    - name: Configure | Static | Create needed folders
      ansible.builtin.file:
        state: directory
        path: "{{ _r_kibana_loop_folders.path }}"
        owner: "{{ _r_kibana_username }}"
        group: "{{ _r_kibana_group }}"
        mode: "{{ _r_kibana_loop_folders.mode }}"
      loop:
        - path: "{{ r_kibana_configuration.path.data }}"
          mode: '755'
      loop_control:
        loop_var: _r_kibana_loop_folders

- name: Configure | Static | Main configuration files
  when: ('main_files' in r_kibana_configure_actions )
  block:
    - name: Configure | Static | Write elasticsearch.yml configuration file
      ansible.builtin.template:
        src: kibana.yml.j2
        dest: "{{ _r_kibana_config_folder }}/kibana.yml"
        mode: 0660
        owner: root
        group: "{{ _r_kibana_group }}"
      notify:
        _r_kibana_configuration_changed

- name: Configure | Static | Keystore management
  when:
    - r_kibana_keystore_password | d(false, true)
    - ('keystore' in r_kibana_configure_actions)
  block:
    - name: Configure | Static | Manage keystore
      bartokit.elastic.kibana_keystore:
        force: "{{  'enforce_keystore' in r_kibana_configure_actions }}"
        credentials: "{{ r_kibana_keystore }}"

- name: Configure | Static | SSL/TLS keystore management
  when:
    - ('ssl' in r_kibana_configure_actions)
    - r_kibana_configuration.server.ssl.enabled | default(false) | bool
  block:
    - name: Configure | Static | Write the ssl key
      ansible.builtin.copy:
        content: "{{ r_kibana_configuration_ssl_key }}"
        dest: "{{ r_kibana_configuration.server.ssl.key }}"
        owner: root
        group: "{{ _r_kibana_group }}"
        mode: '0640'

    - name: Configure | Static | Write the ssl key
      ansible.builtin.copy:
        content: "{{ r_kibana_configuration_ssl_certificate }}"
        dest: "{{ r_kibana_configuration.server.ssl.certificate }}"
        owner: root
        group: "{{ _r_kibana_group }}"
        mode: '0640'

    - name: Configure | Static | Write the CA certificate
      ansible.builtin.copy:
        content: "{{ r_kibana_configuration_ssl_certificate_authorities }}"
        dest: "{{ r_kibana_configuration.elasticsearch.ssl.certificateAuthorities }}"
        owner: root
        group: "{{ _r_kibana_group }}"
        mode: '0660'
      when: r_kibana_configuration_ssl_certificate_authorities is truthy

- name: Flush handlers
  meta: flush_handlers