---
# ---- run behaviour modification ----
# action allowed in r_beat_actions
# - install
# - configure
# - stop
# - upgrade
# - start
# - uninstall
# - restart_on_configuration_change
r_beat_actions: []
_r_beat_actions_allowed:
 - install
 - configure
 - stop
 - upgrade
 - start
 - uninstall
 - restart_on_configuration_change

# more granular configuration actions
r_beat_configure_actions: []
_r_beat_configure_actions_allowed:
  - main_files
  - keystore
  - folders
  - modules
_r_beat_triggered_restart: false

# ---- installation variables ----
r_beat_type:
r_beat_version: '8.11.2'
r_beat_rpm_name: "{{ r_beat_type }}beat"
r_beat_info:
  installed: false
  version: ''
r_beat_add_repository: true

# start && stop
_r_beat_systemd_name: "{{ r_beat_type }}beat.service"

# generic configuration
__r_beat_show_nolog: false   # only for debug purpose


# static configuration
_r_beat_config_folder: "/etc/{{ r_beat_type }}beat"
## password quality settings
_r_beat_password_minlength: 12
_r_beat_password_minuppercase: 3
_r_beat_password_minlowercase: 3
_r_beat_password_mindigits: 2
_r_beat_password_minspecialchars: 1
_r_beat_password_specialchars: '!._@#'

## beat.yml configurations
r_beat_input_path: "{{ _r_beat_config_folder }}/inputs.d"
r_beat_modules_path: "{{ _r_beat_config_folder }}/modules.d"

# variable with inputs
r_beat_inputs: []
_r_beat_modules:
  file: {}
  audit:
    auditd:
      module: auditd
      audit_rule_files:
        - '${path.config}/audit.rules.d/*.conf'
    file_integrity:
      module: file_integrity
      paths:
        - /bin/
        - /usr/bin
        - /sbin
        - /usr/sbin
        - /etc
    system_package:
      module: system
      datasets:
        - package
      period: 2m
      state.period: 3m
    system_other:
      module: system
      datasets:
        - host
        - login
        - process
        - socket
        - user
      state.period: 12h
      user.detect_password_changes: true
      login.wtmp_file_pattern: /var/log/wtmp*
      login.btmp_file_pattern: /var/log/btmp*
  metric: {}

r_beat_modules: {}
# default piece of configuration
_r_beat_configuration:
  file:
    filebeat:
      inputs: "{{ r_beat_inputs }}"
      config:
        inputs:
          enabled: true
          path: "{{ r_beat_input_path }}/*.yml"
          reload:
            enabled: true
            period: 60s
        modules:
          enabled: true
          path: "{{ r_beat_modules_path }}/*.yml"
          reload:
            enabled: true
            period: 60s
  audit:
    auditbeat:
      config:
        modules:
          enabled: true
          path: "{{ r_beat_modules_path }}/*.yml"
          reload:
            enabled: true
            period: 60s
    processors:
      - add_host_metadata: '~'
      - add_cloud_metadata: '~'
      - add_docker_metadata: '~'
  metric: {}
  heart: {}

r_beat_configuration: {}

## keystore settings
_r_beat_keystore: {}
