---
# ---- run behaviour modification ----
# action allowed in r_beat_actions
# - install
# - configure
# - stop
# - upgrade
# - start
# - uninstall
# - restart_on_configuration_change
r_beat_actions: []
_r_beat_actions_allowed:
 - install
 - configure
 - stop
 - upgrade
 - start
 - uninstall
 - restart_on_configuration_change

# more granular configuration actions
r_beat_configure_actions: []
_r_beat_configure_actions_allowed: []
_r_beat_triggered_restart: false

# ---- installation variables ----
r_beat_type:
r_beat_version: '8.11.2'
r_beat_rpm_name: "{{ r_beat_type }}beat"
r_beat_info:
  installed: false
  version: ''
r_beat_add_repository: true

# start && stop
_r_beat_systemd_name: "{{ r_beat_type }}beat.service"

# generic configuration
__r_beat_show_nolog: false   # only for debug purpose


# static configuration
_r_beat_config_folder: /etc/elasticsearch
## password quality settings
_r_beat_password_minlength: 12
_r_beat_password_minuppercase: 3
_r_beat_password_minlowercase: 3
_r_beat_password_mindigits: 2
_r_beat_password_minspecialchars: 1
_r_beat_password_specialchars: '!._@#'

## linux username and password
_r_beat_username: elasticsearch
_r_beat_group: elasticsearch



## elasticsearch.yml configurations
r_beat_node_name: ''
r_beat_node_rack: ''
r_beat_cluster_nodes:
  - host: '{{ ansible_fqdn }}'
    name: '{{ ansible_fqdn }}'
    roles:
      - master
r_beat_cluster_name: 'es_cluster'

_r_beat_configuration:
  network:
    host: "0.0.0.0"
  http:
    host: "0.0.0.0"
    port: 9200
  cluster:
    name: '{{ r_beat_cluster_name }}'
    initial_master_nodes: "{{ r_beat_cluster_nodes | selectattr('roles','bartokit.elastic.contains', 'master') | map(attribute='name') | list }}"
    routing:
      allocation:
        awareness:
          attributes: site_id
  node:
    name: '{{ r_beat_node_name }}'
    roles: >-
      {{ (r_beat_cluster_nodes |
      selectattr('host', 'equalto', ansible_fqdn) | first).roles | list }}
  path:
    logs: /var/log/elasticsearch
    data: /var/lib/elasticsearch
  discovery:
    seed_hosts: "{{ r_beat_cluster_nodes | selectattr('roles','bartokit.elastic.contains', 'master') | map(attribute='name') | list }}"
  xpack:
    security:
      enabled: true
      enrollment:
        enabled: true
      http:
        ssl:
          enabled: true
          verification_mode: certificate
          keystore:
            path: certs/elastic.p12
          certificate_authorities: certs/ca.crt
      transport:
        ssl:
          enabled: true
          verification_mode: certificate
          keystore:
            path: certs/elastic.p12
          certificate_authorities: certs/ca.crt

r_beat_configuration_ssl_certificate_authorities: ''
r_beat_configuration: {}

## keystore settings
r_beat_keystore_password:
r_beat_keystore_password_file: "{{ _r_beat_config_folder }}/keystore.password"
r_beat_keystore:
_r_beat_keystore:
  "bootstrap.password": "{{ r_beat_users_initial_elastic_password }}"

## jvm setting
r_beat_jvm_initial_heap: 1g
r_beat_jvm_maximum_heap: 1g

# admin user and password
r_beat_users_initial_elastic_password: bA3nb0g.Hyw
r_beat_api_password:
r_beat_users: {}
_r_beat_api_user:
  ansible:
    password: "{{ r_beat_api_password }}"
    metadata:
      reserved_to_automation: true
    roles:
      - superuser